name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CHANGELOG_AUTHOR_NAME: "GitHub Actions"
  CHANGELOG_AUTHOR_EMAIL: "no-reply@actions.github.com"

jobs:
  build-debian-package:
    runs-on: ubuntu-latest

    permissions:
      contents: write # required for releases
      packages: write # required for docker image upload

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Patch changelog (snapshot)
        uses: pi-top/git-debian-changelog-bump-action@master
        with:
          release: true
          author_name: ${{ env.CHANGELOG_AUTHOR_NAME }}
          author_email: ${{ env.CHANGELOG_AUTHOR_EMAIL }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply git-debian-changelog-bump-action changes

      - name: Determine current version
        run: |
          sudo apt install -y dpkg-dev
          echo "CURRENT_VERSION=$(dpkg-parsechangelog -Sversion)" >> $GITHUB_ENV

      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign

      - uses: actions/upload-artifact@v2
        with:
          name: redis-bash_${{ env.CURRENT_VERSION }}_all.deb
          path: debian/artifacts/redis-bash_${{ env.CURRENT_VERSION }}_all.deb

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: debian/artifacts/redis-bash_${{ env.CURRENT_VERSION }}_all.deb
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          
