name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CHANGELOG_AUTHOR_NAME: "github-actions[bot]"
  CHANGELOG_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"

jobs:
  build-debian-package:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve app token
        id: app
        uses: Flutter-Tech/github-app-token@v2
        with:
          APP_PEM: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          APP_ID: ${{ secrets.APPLICATION_ID }}
          APP_INSTALLATION_ID: ${{ secrets.APPLICATION_INSTALL_ID }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ steps.app.outputs.app_token }}

      - name: Patch changelog (snapshot)
        uses: pi-top/git-debian-changelog-bump-action@master
        with:
          release: true
          author_name: ${{ env.CHANGELOG_AUTHOR_NAME }}
          author_email: ${{ env.CHANGELOG_AUTHOR_EMAIL }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply git-debian-changelog-bump-action changes

      - name: Apply git-debian-changelog-bump-action changes
        run: |
          if [ ! -z "$(git status --porcelain=v1 2>/dev/null)" ]
          then
            git config --global user.email "${{ env.CHANGELOG_AUTHOR_EMAIL }}"
            git config --global user.name "${{ env.CHANGELOG_AUTHOR_NAME }}"
            git pull --no-edit
            git add -A
            git commit -m "actions generator update"
            git push
          fi

      - name: Determine current version
        run: |
          sudo apt install -y dpkg-dev
          echo "CURRENT_VERSION=$(dpkg-parsechangelog -Sversion)" >> $GITHUB_ENV

      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign

      - uses: actions/upload-artifact@v2
        with:
          name: redis-bash_${{ env.CURRENT_VERSION }}_all.deb
          path: debian/artifacts/redis-bash_${{ env.CURRENT_VERSION }}_all.deb

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: debian/artifacts/redis-bash_${{ env.CURRENT_VERSION }}_all.deb
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          
